services:
  db:
    build: .
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cvelang
    ports:
      - "5432:5432"
    volumes:
      - cvelang_db_data:/var/lib/postgresql/data
      - ./cvelang/sql:/usr/share/cvelang/sql

volumes:
  cvelang_db_data: