services:
  db:
    build: .
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: langcve
    ports:
      - "5432:5432"
    volumes:
      - langcve_db_data:/var/lib/postgresql/data

volumes:
  langcve_db_data:
